config/routes.rb
AmoebaCircus::Application.routes.draw do

  resources :amoebas
  resources :acts

end

app/models/act.rb
class Act < ActiveRecord::Base

  has_many :amoebas
  has_many :talents, through: :amoebas

end

app/models/amoeba.rb
class Amoeba < ActiveRecord::Base
  
  belongs_to :acts
  belongs_to :talents

end

app/models/talent.rb
class Talent < ActiveRecord::Base

  has_many :amoebas

end

app/controllers/acts_controller.rb
class ActsController < ApplicationController

  def index
    @acts = Act.all
  end

  def new
    @act = Act.new
  end

  def create
    @act = Act.new(params[:act])
    if @act.save
      redirect_to @act
    else
      render new
    end
  end

  def show
    @act = Act.find(params[:id])
  end

  def edit
    @act = Act.find(params[:id])
  end

  def update
    @act = Act.find(params[:id])
    if @act.update_attributes(params[:act])
      redirect_to @act
    else
      render edit
    end
  end

  def destroy
    @act = Act.find(params[:id])
    @act.destroy
    redirect_to acts_url
  end

end

app/controllers/amoebas_controller.rb
class AmoebasController < ApplicationController
  def index
    @amoebas = Amoeba.all
  end

  def new
    @amoeba = Amoeba.new
  end

  def create
    @amoeba = Amoeba.new(params[:amoeba])
    if @amoeba.save
      redirect_to @amoeba
    else
      render new
    end
  end

  def show
    @amoeba = Amoeba.find(params[:id])
  end

  def edit
    @amoeba = Amoeba.find(params[:id])
  end

  def update
    @amoeba = Amoeba.find(params[:id])
    if @amoeba.update_attributes(params[:amoeba])
      redirect_to @amoeba
    else
      render edit
    end
  end

  def destroy
    @amoeba = Amoeba.find(params[:id])
    @amoeba.destroy
    redirect_to amoebas_url
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @amoebas = Amoeba.all
    @acts = Act.all
  end

end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/amoebas_helper.rb
module AmoebasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/acts/_form.html.erb
<%= form_for(@act) do |f| %>
  <% if @act.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@act.errors.count, "error") %> prohibited this act from being saved:</h2>

      <ul>
      <% @act.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :performance_date %><br>
    <%= f.datetime_select :performance_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acts/_form.html.haml
= form_for @act do |f|
  - if @act.errors.any?
    #error_explanation
      %h2= "#{pluralize(@act.errors.count, "error")} prohibited this act from being saved:"
      %ul
        - @act.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :date
    = f.text_field :date

  .field
    = f.label :time
    = f.text_field :time

  .actions
    = f.submit

app/views/acts/edit.html.erb
<h1>Editing act</h1>

<%= render 'form' %>

<%= link_to 'Show', @act %> |
<%= link_to 'Back', acts_path %>

app/views/acts/edit.html.haml
%h1= "Edit #{@act.name}"

= render "form"

%br

= link_to "Act List", acts_path

app/views/acts/index.html.erb
<h1>Acts</h1>

<% @acts.each do |act| %>
  <p>
    name: <%= link_to act.name, act_path(act) %><br>
    date: <%= act.performance_date %>
  </p>
  </tr>
<% end %>

<p><strong><%= link_to 'New Act', new_act_path %></strong></p>

app/views/acts/index.html.haml
%h1 Acts for the Grand Show!

%table
  %tr
    %th Name
    %th Date
    %th Time
    %th
    %th
    %th

  - @acts.each do |act|
    %tr
      %td= act.name
      %td= act.date
      %td= act.time
      %td= link_to "Show", act
      %td= link_to "Edit", edit_act_path(act)
      %td= link_to "Delete", act, :method => 'delete', :data => {:confirm => "Are you sure you've performed this act for the last time?"}
%br
%br
= link_to "New Act", new_act_path

app/views/acts/new.html.erb
<h1>New act</h1>

<%= render 'form' %>

<%= link_to 'Back', acts_path %>

app/views/acts/new.html.haml
%h1 New Act

= render "form"

%br

= link_to "All Acts", acts_path

app/views/acts/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @act.name %></h1>

<p>
  <strong>Date:</strong>
  <%= @act.performance_date %>
</p>

<h2>Performers</h2>
<ul>
  <% @act.amoebas.each do |amoeba| %>
    <li><%= link_to amoeba.name, amoeba_path(amoeba) %></li>
  <%end %>
</ul>

<%= link_to 'Edit', edit_act_path(@act) %> | 
<%=link_to "Delete",act_path(@act), 'data-method' => :delete, :class => "delete", :confirm => "Are you sure ?"%> | 
<%= link_to 'Back', acts_path %>

app/views/acts/show.html.haml
%h1= @act.name

%ul
  %li= "Name: #{@act.name}"
  %li= "Date: #{@act.date}"
  %li= "Time: #{@act.time }"

= link_to "All Acts", acts_path
= link_to "Edit Act", edit_act_path(@act)

app/views/amoebas/_form.html.erb
<%= form_for(@amoeba) do |f| %>
  <% if @amoeba.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amoeba.errors.count, "error") %> prohibited this amoeba from being saved:</h2>

      <ul>
      <% @amoeba.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :talent_id %><br>
    <select name="talent_id">
    <% @talents.each do |talent| %>
      <option value="<%= talent.name %>" <% if @amoeba.talent_id == talent.id %>selected<% end %>><%= talent.name %></option>
    <% end %>
    </select>
  </div>
  <div class="field">
    <%= f.label :act_id %><br>
    <select name="act_id">
    <% @acts.each do |act| %>
      <option value="<%= act.name %>" <% if @amoeba.talent_id == act.id %>selected<% end %>><%= act.name %></option>
    <% end %>
    </select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amoebas/_form.html.haml
= form_for @amoeba do |f|
  - if @amoeba.errors.any?
    #error_explanation
      %h2= "#{pluralize(@amoeba.errors.count, "error")} prohibited this amoeba from being saved:"
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :talent
    = f.number_field :talent_id

  .field
    = f.label :act
    = f.number_field :act_id

  .actions
    = f.submit

app/views/amoebas/edit.html.erb
<h1>Editing amoeba</h1>

<%= render 'form' %>

<%= link_to 'Show', @amoeba %> |
<%= link_to 'Back', amoebas_path %>

app/views/amoebas/edit.html.haml
%h1= "Edit #{@amoeba.name}"

= render 'form'

%br

= link_to "Amoeba List", amoebas_path

app/views/amoebas/index.html.erb
<h1>Amoebas</h1>

<% @amoebas.each do |amoeba| %>
  <p><%= link_to amoeba.name, amoeba_path(amoeba) %></p>
<% end %>

app/views/amoebas/index.html.haml
%h1 All Amoebas

%table
  %tr
    %th Name
    %th Generation
    %th Talent
    %th Act
    %th
    %th
    %th
  - @amoebas.each do |amoeba|
    %tr
      %td= amoeba.name
      %td= amoeba.generation
      %td= amoeba.talent_id
      %td= amoeba.act_id
      %td= link_to "Show", amoeba
      %td= link_to "Edit", edit_amoeba_path(amoeba)
      %td= link_to "Delete", amoeba, :method => 'delete', :data => {:confirm => "Are you sure you want to kill this amoeba?"}
%br
%br
= link_to 'New Amoeba', new_amoeba_path

app/views/amoebas/new.html.erb
<h1>New amoeba</h1>

<%= render 'form' %>

<%= link_to 'Back', amoebas_path %>

app/views/amoebas/new.html.haml
%h1 A New Amoeba Is Born!

= render "form"

%br

= link_to "All_Amoebas", amoebas_path

app/views/amoebas/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @amoeba.name %></h1>

<p>
  <strong>Talent:</strong>
  <%= @amoeba.talent.name %>
</p>

<p>
  <strong>Generation:</strong>
  <%= @amoeba.generation %>
</p>

<p>
  <strong>Act:</strong>
  <%= link_to @amoeba.act.name, act_path(@amoeba.act) %>
</p>

<p><strong><a href="/amoebas/<%= @amoeba.id %>/split">Split</a></strong></p>

<%= link_to 'Edit', edit_amoeba_path(@amoeba) %> |
<%=link_to "Delete",amoeba_path(@amoeba), 'data-method' => :delete, :class => "delete", :confirm => "Are you sure ?"%> | 
<%= link_to 'Back', amoebas_path %>

app/views/amoebas/show.html.haml
%h1= @amoeba.name

%ul
  %li= "Name: #{@amoeba.name}"
  %li= "Generation: #{@amoeba.generation}"
  %li= "Act: #{@amoeba.act_id}"
  %li= "Talent: #{@amoeba.talent_id}"

= link_to "Amoeba List", amoebas_path
= link_to "Edit", edit_amoeba_path(@amoeba)

app/views/amoebas/split.html.erb
<h1>Split <%= @amoeba.name %> Into:</h1>
<%= form_tag "/amoebas/splitter", :method => "post" do %>
  <input type="hidden" name="original_id" value="<%= @amoeba.id %>">
  <input type="hidden" name="generation" value="<%= @amoeba.generation %>">
  <input type="hidden" name="talent_id" value="<%= @amoeba.talent_id %>">
  <input type="hidden" name="act_id" value="<%= @amoeba.act_id %>">
  <label for="amoeba_one">Amoeba One's Name</label>
  <input type="text" id="amoeba_one" name="name1"><br>
  <label for="amoeba_two">Amoeba Two's Name</label>
  <input type="text" id="amoeba_two" name="name2"><br>
  <input type="submit" value="split">
<% end %>
<p><%= link_to 'Cancel', amoebas_path %></p>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>
<div id="amoebas">
  <h2>Amoebas</h2>
  <% @amoebas.each do |amoeba| %>
    <p><%= link_to amoeba.name, amoeba_path(amoeba) %></p>
  <% end %>
</div>
<div id="acts">
  <h2>Acts</h2>
  <% @acts.each do |act| %>
    <p><%= link_to act.name, act_path(act) %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmoebaCircus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>